// <auto-generated />
using System;
using AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(MedicalContext))]
    [Migration("20260514030230_UpdateFoto")]
    partial class UpdateFoto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Doctor", b =>
                {
                    b.Property<int>("Id_Doctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Doctor"));

                    b.Property<string>("AlmaMater")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<int>("Id_Especialidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id_Doctor");

                    b.HasIndex("Id_Especialidad");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id_Doctor = 1,
                            AlmaMater = "Universidad de El Salvador",
                            Apellido = "Martínez",
                            Foto = "/img/doctores/doc1.png",
                            HoraEntrada = new TimeSpan(0, 8, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 15, 0, 0, 0),
                            Id_Especialidad = 1,
                            Nombre = "Carlos",
                            Perfil = "Médico general con enfoque en atención primaria y medicina preventiva. Graduado de la Universidad de El Salvador, cuenta con amplia experiencia en el manejo de enfermedades crónicas y seguimiento integral del paciente adulto."
                        },
                        new
                        {
                            Id_Doctor = 2,
                            AlmaMater = "Universidad Dr. José Matías Delgado",
                            Apellido = "Fernández",
                            Foto = "/img/doctores/doc2.png",
                            HoraEntrada = new TimeSpan(0, 8, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 16, 0, 0, 0),
                            Id_Especialidad = 1,
                            Nombre = "Lucía",
                            Perfil = "Especialista en medicina comunitaria con formación en la Universidad Dr. José Matías Delgado. Experta en diagnósticos clínicos tempranos, promoción de la salud y atención de urgencias menores en el ámbito clínico privado."
                        },
                        new
                        {
                            Id_Doctor = 3,
                            AlmaMater = "Universidad Evangélica",
                            Apellido = "Rivas",
                            Foto = "/img/doctores/doc3.png",
                            HoraEntrada = new TimeSpan(0, 9, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 17, 0, 0, 0),
                            Id_Especialidad = 5,
                            Nombre = "Elena",
                            Perfil = "Psicóloga clínica con maestría en terapia cognitivo-conductual. Se especializa en el tratamiento de trastornos de ansiedad, depresión y manejo del estrés, brindando un enfoque humano y empático en cada sesión terapéutica."
                        },
                        new
                        {
                            Id_Doctor = 4,
                            AlmaMater = "Universidad de El Salvador",
                            Apellido = "Orellana",
                            Foto = "/img/doctores/doc4.png",
                            HoraEntrada = new TimeSpan(0, 11, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 19, 0, 0, 0),
                            Id_Especialidad = 5,
                            Nombre = "Samuel",
                            Perfil = "Profesional de la salud mental graduado de la UES, con experticia en psicología organizacional y apoyo psicopedagógico. Enfocado en el desarrollo de resiliencia y salud mental en entornos laborales y académicos."
                        },
                        new
                        {
                            Id_Doctor = 5,
                            AlmaMater = "Universidad de El Salvador",
                            Apellido = "Zelaya",
                            Foto = "/img/doctores/doc6.png",
                            HoraEntrada = new TimeSpan(0, 10, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 18, 0, 0, 0),
                            Id_Especialidad = 2,
                            Nombre = "Beatriz",
                            Perfil = "Odontóloga integral con énfasis en rehabilitación oral y estética dental. Graduada de la Universidad de El Salvador, es experta en tratamientos preventivos y restaurativos, enfocada en devolver la funcionalidad y armonía estética a la sonrisa."
                        },
                        new
                        {
                            Id_Doctor = 6,
                            AlmaMater = "Universidad Dr. José Matías Delgado",
                            Apellido = "Arias",
                            Foto = "/img/doctores/doc7.png",
                            HoraEntrada = new TimeSpan(0, 7, 30, 0, 0),
                            HoraSalida = new TimeSpan(0, 15, 30, 0, 0),
                            Id_Especialidad = 3,
                            Nombre = "Patricia",
                            Perfil = "Especialista en el cuidado integral de la infancia y adolescencia. Con formación en la Universidad Dr. José Matías Delgado, destaca por su paciencia y precisión en el control de niño sano y desarrollo infantil."
                        },
                        new
                        {
                            Id_Doctor = 7,
                            AlmaMater = "Universidad de El Salvador",
                            Apellido = "Méndez",
                            Foto = "/img/doctores/doc8.png",
                            HoraEntrada = new TimeSpan(0, 8, 30, 0, 0),
                            HoraSalida = new TimeSpan(0, 16, 30, 0, 0),
                            Id_Especialidad = 4,
                            Nombre = "Gustavo",
                            Perfil = "Ginecólogo y obstetra dedicado a la salud integral de la mujer en todas sus etapas. Experto en control prenatal, planificación familiar y cirugía ginecológica mínimamente invasiva."
                        },
                        new
                        {
                            Id_Doctor = 8,
                            AlmaMater = "Universidad Alberto Masferrer",
                            Apellido = "Valle",
                            Foto = "/img/doctores/doc5.png",
                            HoraEntrada = new TimeSpan(0, 8, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 12, 0, 0, 0),
                            Id_Especialidad = 6,
                            Nombre = "Ricardo",
                            Perfil = "Médico cirujano oftalmólogo con especialización en el diagnóstico de patologías oculares, corrección de errores refractivos y prevención del glaucoma. Comprometido con la salud visual de sus pacientes."
                        });
                });

            modelBuilder.Entity("Entidades.Especialidad", b =>
                {
                    b.Property<int>("Id_Especialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Especialidad"));

                    b.Property<string>("Nombre_especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Especialidad");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id_Especialidad = 1,
                            Nombre_especialidad = "Medicina General"
                        },
                        new
                        {
                            Id_Especialidad = 2,
                            Nombre_especialidad = "Odontología"
                        },
                        new
                        {
                            Id_Especialidad = 3,
                            Nombre_especialidad = "Pedriatría"
                        },
                        new
                        {
                            Id_Especialidad = 4,
                            Nombre_especialidad = "Ginecología"
                        },
                        new
                        {
                            Id_Especialidad = 5,
                            Nombre_especialidad = "Psicología"
                        },
                        new
                        {
                            Id_Especialidad = 6,
                            Nombre_especialidad = "Oftalmologia"
                        });
                });

            modelBuilder.Entity("Entidades.Doctor", b =>
                {
                    b.HasOne("Entidades.Especialidad", "Especialidad")
                        .WithMany("Doctors")
                        .HasForeignKey("Id_Especialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("Entidades.Especialidad", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
