// <auto-generated />
using System;
using AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(MedicalContext))]
    [Migration("20260515220340_FechaCitaTimeSpan")]
    partial class FechaCitaTimeSpan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Citas", b =>
                {
                    b.Property<int>("Id_Citas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Citas"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("Id_Paciente")
                        .HasColumnType("int");

                    b.Property<int>("Id_doctor")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("doctor")
                        .HasColumnType("int");

                    b.Property<int>("paciente")
                        .HasColumnType("int");

                    b.HasKey("Id_Citas");

                    b.HasIndex("Id_Paciente");

                    b.HasIndex("Id_doctor");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Entidades.Doctor", b =>
                {
                    b.Property<int>("Id_Doctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Doctor"));

                    b.Property<string>("AlmaMater")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Foto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<int>("Id_Especialidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Perfil")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id_Doctor");

                    b.HasIndex("Id_Especialidad");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id_Doctor = 1,
                            AlmaMater = "Universidad de El Salvador",
                            Foto = "/img/doctores/doc1.png",
                            HoraEntrada = new TimeSpan(0, 8, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 15, 0, 0, 0),
                            Id_Especialidad = 1,
                            Id_Usuario = 1,
                            Perfil = "Médico general con enfoque en atención primaria y medicina preventiva. Graduado de la Universidad de El Salvador, cuenta con amplia experiencia en el manejo de enfermedades crónicas y seguimiento integral del paciente adulto."
                        },
                        new
                        {
                            Id_Doctor = 2,
                            AlmaMater = "Universidad Dr. José Matías Delgado",
                            Foto = "/img/doctores/doc2.png",
                            HoraEntrada = new TimeSpan(0, 8, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 16, 0, 0, 0),
                            Id_Especialidad = 1,
                            Id_Usuario = 2,
                            Perfil = "Especialista en medicina comunitaria con formación en la Universidad Dr. José Matías Delgado. Experta en diagnósticos clínicos tempranos, promoción de la salud y atención de urgencias menores en el ámbito clínico privado."
                        },
                        new
                        {
                            Id_Doctor = 3,
                            AlmaMater = "Universidad Evangélica",
                            Foto = "/img/doctores/doc3.png",
                            HoraEntrada = new TimeSpan(0, 9, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 17, 0, 0, 0),
                            Id_Especialidad = 5,
                            Id_Usuario = 3,
                            Perfil = "Psicóloga clínica con maestría en terapia cognitivo-conductual. Se especializa en el tratamiento de trastornos de ansiedad, depresión y manejo del estrés, brindando un enfoque humano y empático en cada sesión terapéutica."
                        },
                        new
                        {
                            Id_Doctor = 4,
                            AlmaMater = "Universidad de El Salvador",
                            Foto = "/img/doctores/doc4.png",
                            HoraEntrada = new TimeSpan(0, 11, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 19, 0, 0, 0),
                            Id_Especialidad = 5,
                            Id_Usuario = 4,
                            Perfil = "Profesional de la salud mental graduado de la UES, con experticia en psicología organizacional y apoyo psicopedagógico. Enfocado en el desarrollo de resiliencia y salud mental en entornos laborales y académicos."
                        },
                        new
                        {
                            Id_Doctor = 5,
                            AlmaMater = "Universidad de El Salvador",
                            Foto = "/img/doctores/doc6.png",
                            HoraEntrada = new TimeSpan(0, 10, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 18, 0, 0, 0),
                            Id_Especialidad = 2,
                            Id_Usuario = 5,
                            Perfil = "Odontóloga integral con énfasis en rehabilitación oral y estética dental. Graduada de la Universidad de El Salvador, es experta en tratamientos preventivos y restaurativos, enfocada en devolver la funcionalidad y armonía estética a la sonrisa."
                        },
                        new
                        {
                            Id_Doctor = 6,
                            AlmaMater = "Universidad Dr. José Matías Delgado",
                            Foto = "/img/doctores/doc7.png",
                            HoraEntrada = new TimeSpan(0, 7, 30, 0, 0),
                            HoraSalida = new TimeSpan(0, 15, 30, 0, 0),
                            Id_Especialidad = 3,
                            Id_Usuario = 6,
                            Perfil = "Especialista en el cuidado integral de la infancia y adolescencia. Con formación en la Universidad Dr. José Matías Delgado, destaca por su paciencia y precisión en el control de niño sano y desarrollo infantil."
                        },
                        new
                        {
                            Id_Doctor = 7,
                            AlmaMater = "Universidad de El Salvador",
                            Foto = "/img/doctores/doc8.png",
                            HoraEntrada = new TimeSpan(0, 8, 30, 0, 0),
                            HoraSalida = new TimeSpan(0, 16, 30, 0, 0),
                            Id_Especialidad = 4,
                            Id_Usuario = 7,
                            Perfil = "Ginecólogo y obstetra dedicado a la salud integral de la mujer en todas sus etapas. Experto en control prenatal, planificación familiar y cirugía ginecológica mínimamente invasiva."
                        },
                        new
                        {
                            Id_Doctor = 8,
                            AlmaMater = "Universidad Alberto Masferrer",
                            Foto = "/img/doctores/doc5.png",
                            HoraEntrada = new TimeSpan(0, 8, 0, 0, 0),
                            HoraSalida = new TimeSpan(0, 12, 0, 0, 0),
                            Id_Especialidad = 6,
                            Id_Usuario = 8,
                            Perfil = "Médico cirujano oftalmólogo con especialización en el diagnóstico de patologías oculares, corrección de errores refractivos y prevención del glaucoma. Comprometido con la salud visual de sus pacientes."
                        });
                });

            modelBuilder.Entity("Entidades.Especialidad", b =>
                {
                    b.Property<int>("Id_Especialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Especialidad"));

                    b.Property<string>("Nombre_especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Especialidad");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id_Especialidad = 1,
                            Nombre_especialidad = "Medicina General"
                        },
                        new
                        {
                            Id_Especialidad = 2,
                            Nombre_especialidad = "Odontología"
                        },
                        new
                        {
                            Id_Especialidad = 3,
                            Nombre_especialidad = "Pediatría"
                        },
                        new
                        {
                            Id_Especialidad = 4,
                            Nombre_especialidad = "Ginecología"
                        },
                        new
                        {
                            Id_Especialidad = 5,
                            Nombre_especialidad = "Psicología"
                        },
                        new
                        {
                            Id_Especialidad = 6,
                            Nombre_especialidad = "Oftalmología"
                        });
                });

            modelBuilder.Entity("Entidades.Usuarios", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DUI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDoctor")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("DUI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id_Usuario = 1,
                            Apellido = "Martínez",
                            DUI = "10000000-1",
                            Email = "carlos.martinez@clinica.com",
                            IsDoctor = true,
                            Nombre = "Carlos",
                            password = "$2a$12$cyyvGxCZnMpifroR0sUy4uvTZb5rh9ojoyD8jDozLjpXI9zGc5FBG"
                        },
                        new
                        {
                            Id_Usuario = 2,
                            Apellido = "Fernández",
                            DUI = "10000001-2",
                            Email = "lucia.fernandez@clinica.com",
                            IsDoctor = true,
                            Nombre = "Lucía",
                            password = "$2a$12$cyyvGxCZnMpifroR0sUy4uvTZb5rh9ojoyD8jDozLjpXI9zGc5FBG"
                        },
                        new
                        {
                            Id_Usuario = 3,
                            Apellido = "Rivas",
                            DUI = "10000002-3",
                            Email = "elena.rivas@clinica.com",
                            IsDoctor = true,
                            Nombre = "Elena",
                            password = "$2a$12$cyyvGxCZnMpifroR0sUy4uvTZb5rh9ojoyD8jDozLjpXI9zGc5FBG"
                        },
                        new
                        {
                            Id_Usuario = 4,
                            Apellido = "Orellana",
                            DUI = "10000003-4",
                            Email = "samuel.orellana@clinica.com",
                            IsDoctor = true,
                            Nombre = "Samuel",
                            password = "$2a$12$cyyvGxCZnMpifroR0sUy4uvTZb5rh9ojoyD8jDozLjpXI9zGc5FBG"
                        },
                        new
                        {
                            Id_Usuario = 5,
                            Apellido = "Zelaya",
                            DUI = "10000004-5",
                            Email = "beatriz.zelaya@clinica.com",
                            IsDoctor = true,
                            Nombre = "Beatriz",
                            password = "$2a$12$cyyvGxCZnMpifroR0sUy4uvTZb5rh9ojoyD8jDozLjpXI9zGc5FBG"
                        },
                        new
                        {
                            Id_Usuario = 6,
                            Apellido = "Arias",
                            DUI = "10000005-6",
                            Email = "patricia.arias@clinica.com",
                            IsDoctor = true,
                            Nombre = "Patricia",
                            password = "$2a$12$cyyvGxCZnMpifroR0sUy4uvTZb5rh9ojoyD8jDozLjpXI9zGc5FBG"
                        },
                        new
                        {
                            Id_Usuario = 7,
                            Apellido = "Méndez",
                            DUI = "10000006-7",
                            Email = "gustavo.mendez@clinica.com",
                            IsDoctor = true,
                            Nombre = "Gustavo",
                            password = "$2a$12$cyyvGxCZnMpifroR0sUy4uvTZb5rh9ojoyD8jDozLjpXI9zGc5FBG"
                        },
                        new
                        {
                            Id_Usuario = 8,
                            Apellido = "Valle",
                            DUI = "10000007-8",
                            Email = "ricardo.valle@clinica.com",
                            IsDoctor = true,
                            Nombre = "Ricardo",
                            password = "$2a$12$cyyvGxCZnMpifroR0sUy4uvTZb5rh9ojoyD8jDozLjpXI9zGc5FBG"
                        });
                });

            modelBuilder.Entity("Entidades.Citas", b =>
                {
                    b.HasOne("Entidades.Usuarios", "Paciente")
                        .WithMany("CitasPaciente")
                        .HasForeignKey("Id_Paciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades.Doctor", "Doctor")
                        .WithMany("CitasRegistradas")
                        .HasForeignKey("Id_doctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Entidades.Doctor", b =>
                {
                    b.HasOne("Entidades.Especialidad", "Especialidad")
                        .WithMany("Doctores")
                        .HasForeignKey("Id_Especialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Usuarios", "usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Entidades.Doctor", b =>
                {
                    b.Navigation("CitasRegistradas");
                });

            modelBuilder.Entity("Entidades.Especialidad", b =>
                {
                    b.Navigation("Doctores");
                });

            modelBuilder.Entity("Entidades.Usuarios", b =>
                {
                    b.Navigation("CitasPaciente");
                });
#pragma warning restore 612, 618
        }
    }
}
